# Alabaster (light)
set -g status-style 'bg=#ededed fg=#000000'
set -g window-status-current-style 'bg=#bfdbfe fg=#325cc0 bold'
set -g window-status-style 'bg=#ededed fg=#777777'
set -g pane-border-style 'fg=#cccccc'
set -g pane-active-border-style 'fg=#325cc0'
set -g message-style 'bg=#ededed fg=#000000'
