
host=$(command -v scutil &> /dev/null && scutil --get LocalHostName || hostname)

# Different things to initialize depending on which computer I'm using
case $host in
    "phil-macbook-air")
	# Set PATH, MANPATH, etc., for Homebrew.
	eval "$(/opt/homebrew/bin/brew shellenv)"
	# Set PATH for Sublime Text and VSCode
	export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"
	export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
	eval "$(/opt/homebrew/bin/brew shellenv)"
	;;

    "phils-mbp")
	# Set PATH for Sublime Text and VSCode
	export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"
	export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
	eval "$(/opt/homebrew/bin/brew shellenv)"
	;;
    "HQDTWHG4VP")
	eval "$(/opt/homebrew/bin/brew shellenv)"
	;;
    "raspi")
	;;
    *)
        echo -n "computer $host not recognized"
        ;;
esac

