#!/bin/zsh

# ====== GENERAL ======

export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
# some apps try to pass the entire $EDITOR string to env as a single argument.
# this wrapper function works around that issue.
export EDITOR="emacsclient-term"
ZSH_THEME="clean-custom" #"fwalch"

# get the hostname. works on both macos and linux.
host=$(command -v scutil &> /dev/null && scutil --get LocalHostName || hostname)

case $host in
    "phil-macbook-air")
        # ====== Personal macbook scripts, aliases, etc. ======
        export ZSH="/Users/phil/.oh-my-zsh"
        export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"

        plugins=(
            git
        )

        # add ruby and dotfile scripts to my path
        export PATH="/opt/homebrew/opt/ruby/bin:/Users/phil/Library/Python/3.11/bin:/opt/homebrew/lib/ruby/gems/3.2.0/bin:$PATH"

        # store secrets in a separate file that's outside of my dotfiles
        source ~/.secrets
        export DENO_INSTALL="/Users/phil/.deno"
        export PATH="$DENO_INSTALL/bin:$PATH"
        # initiate https://github.com/tobi/try
        eval "$(ruby ~/.local/try.rb init ~/tries)"
        ;;
    "HQDTWHG4VP")
        export ZSH="/Users/phil.catterall/.oh-my-zsh"
        export NVM_DIR="$HOME/.nvm"
        # Lazy load nvm - only initialize when actually needed
        nvm() {
            unset -f nvm
            [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
            nvm "$@"
        }
        node() {
            unset -f node nvm
            [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
            node "$@"
        }
        npm() {
            unset -f npm nvm
            [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
            npm "$@"
        }
        yarn() {
            unset -f yarn nvm
            [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
            yarn "$@"
        }
        alias mdm='cd ~/src/universe/experimental/phil-catterall_data/mdm-prototype'
        alias lg='lazygit'
        ;;
    "raspi")
        export COLORTERM=truecolor
        export ZSH="/home/phil/.oh-my-zsh"
        export DENO_INSTALL="/Users/phil/.deno"
        export PATH="$DENO_INSTALL/bin:$PATH"
        export PATH="$PATH:$HOME/go/bin"
        plugins=(
            git
        )
        # fnm (fast node manager) - replaces nvm
        export PATH="$HOME/.local/share/fnm:$PATH"
        eval "$(fnm env)"
        ;;
    *)
        echo -n "computer $host not recognized"
esac

DISABLE_AUTO_TITLE="true"
source $ZSH/oh-my-zsh.sh

# ====== ALIASES ======

# lf file manager stuff
lfcd () {
    # `command` is needed in case `lfcd` is aliased to `lf`
    cd "$(command lf -print-last-dir "$@")"
}

alias lf='lfcd'

# fzf
export FZF_DEFAULT_OPTS='--height 40% --reverse'

# emacs
alias e='emacsclient -t'           # Terminal emacs
alias ec='emacsclient -c'          # GUI emacs

# make a directory, then cd into it.
mkcd () {
  \mkdir -p "$1"
  cd "$1"
}

# create a temp directory and cds into it
tempe () {
  cd "$(mktemp -d)"
  chmod -R 0700 .
  if [[ $# -eq 1 ]]; then
    \mkdir -p "$1"
    cd "$1"
    chmod -R 0700 .
  fi
}

# rename the current iTerm tab
tab () { echo -ne "\033]0;$1\007" }

alias gs='git status'

# soft serve git server
alias sst='ssh -p 23231 git.tail75bb5.ts.net'
ssr() { ssh -p 23231 git.tail75bb5.ts.net repo create "$1"; }

# pnpm
export PNPM_HOME="/Users/phil/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# use fzf for shell command history
source <(fzf --zsh)   # zsh
